# -*- coding: utf-8 -*-
"""final_ft4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GcW6OkZj_ogGTKyQFiO4ien6cE0_KqQU
"""

import pandas as pd

BASE_URL = "https://azure.abhi.dedyn.io/iot/"
OUTPUT_CSV = "final_labeled_data.csv"

# Desired column headers
COLUMNS = [
    "temperature",
    "pressure",
    "humidity",
    "gas",
    "aqi",
    "time_stamp_esp",
    "time_stamp_server"
]

all_data = []
file_index = 1

while True:
    try:
        file_url = f"{BASE_URL}csv_data_{file_index}.csv"
        print(f"Fetching: {file_url}")

        # Read CSV without header
        df = pd.read_csv(file_url, header=None)

        # Validate column count
        if df.shape[1] != len(COLUMNS):
            print(f"Column mismatch in csv_data_{file_index}.csv — stopping.")
            break

        # Assign headers
        df.columns = COLUMNS

        all_data.append(df)
        file_index += 1

    except Exception as e:
        print(f"No more files found. Stopping at csv_data_{file_index - 1}.csv")
        break

# Combine all CSVs
final_df = pd.concat(all_data, ignore_index=True)

# Save final CSV
final_df.to_csv(OUTPUT_CSV, index=False)

print(f"\n✅ Final CSV saved as: {OUTPUT_CSV}")
print(f"Total rows collected: {len(final_df)}")

# import pandas as pd

# # Path to your original CSV file
# input_csv = "csv_data.csv"     # change this to your actual file name
# output_csv = "labeled_data.csv"

# # Define the headers you want
# columns = [
#     "temperature",
#     "pressure",
#     "humidity",
#     "gas",
#     "aqi",
#     "time_stamp_esp",
#     "time_stamp_server"
# ]

# # Read CSV WITHOUT header
# df = pd.read_csv(input_csv, header=None)

# # Assign column names
# df.columns = columns

# # Save the new CSV
# df.to_csv(output_csv, index=False)

# print("New CSV saved with headers successfully!")

"""🧩 CELL 1 — Load, Sort, and Prepare Base Features"""

import pandas as pd
import numpy as np

# Load data
df = pd.read_csv("final_labeled_data.csv")

# Sort by time (CRITICAL for time series)
df = df.sort_values("time_stamp_esp").reset_index(drop=True)

print("Data loaded & sorted")
print(df.head(3))
print("Rows:", len(df))

"""🧩 CELL 2 — Pollution Aggregation (Gas + AQI)"""

# Percentiles for normalization
gas_q80 = df['gas'].quantile(0.8)
aqi_q80 = df['aqi'].quantile(0.8)

# Normalize
df['gas_norm'] = df['gas'] / gas_q80
df['aqi_norm'] = df['aqi'] / aqi_q80

# Aggregated pollution index
df['pollution_index'] = (
    0.6 * df['gas_norm'] +
    0.4 * df['aqi_norm']
)

print(df[['gas_norm','aqi_norm','pollution_index']].describe())

"""🧩 CELL 3 — Logical Labeling (Safe & Deterministic)"""

hum_q20  = df['humidity'].quantile(0.2)
hum_q80  = df['humidity'].quantile(0.8)
temp_q20 = df['temperature'].quantile(0.2)
temp_q80 = df['temperature'].quantile(0.8)

def assign_label(row, margin=0.15):
    scores = {
        "polluted": row["pollution_index"],
        "humid": row["humidity"] / hum_q80,
        "dry": hum_q20 / max(row["humidity"], 1),
        "hot": row["temperature"] / temp_q80,
        "cold": temp_q20 / max(row["temperature"], 1),
    }

    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    top, top_val = sorted_scores[0]
    second, sec_val = sorted_scores[1]

    if top_val < 1.0:
        return "comfortable"
    if abs(top_val - sec_val) < margin:
        return "uncomfortable"
    if top == "polluted":
        return "polluted"
    return "uncomfortable"

df["label"] = df.apply(assign_label, axis=1)

print(df["label"].value_counts())

"""🧩 CELL 4 — Reduce Labels (TinyML-Optimal)"""

def reduce_label(lbl):
    if lbl == "polluted":
        return "polluted"
    if lbl == "comfortable":
        return "comfortable"
    return "uncomfortable"

df["label_final"] = df["label"].apply(reduce_label)
df.to_csv("row_level_labeled_timeseries.csv", index=False)

print("✅ Saved: row_level_labeled_timeseries.csv")
print("Columns:")
print(df.columns.tolist())
print("\nSample rows:")
print(df.head(5))

print("Final labels:")
print(df["label_final"].value_counts())

"""🧩 CELL 5 — Build Sliding Windows (Time Series Core)"""

WINDOW_SIZE = 8
FEATURES = ['temperature','humidity','pressure','pollution_index']

# Scaling (MUST match Arduino)
def scale_row(row):
    return np.array([
        row[0] / 50.0,
        row[1] / 100.0,
        (row[2] - 1000.0) / 50.0,
        row[3] / 2.0
    ], dtype=np.float32)

X, y = [], []

for i in range(len(df) - WINDOW_SIZE):
    window = df.iloc[i:i+WINDOW_SIZE][FEATURES].values
    window_scaled = np.array([scale_row(r) for r in window])
    X.append(window_scaled)
    y.append(df.iloc[i+WINDOW_SIZE-1]["label_final"])

X = np.array(X)
y = np.array(y)

print("Windowed shape:", X.shape)
print("Labels:", np.unique(y))

"""CELL 6 — Encode Labels & Train/Test Split"""

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
y_enc = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc,
    test_size=0.2,
    stratify=y_enc,
    random_state=42
)

print("Classes:", le.classes_)
X_flat = X.reshape(X.shape[0], -1)

feature_names = []
for t in range(WINDOW_SIZE):
    feature_names += [
        f"temp_t-{WINDOW_SIZE-1-t}",
        f"hum_t-{WINDOW_SIZE-1-t}",
        f"press_t-{WINDOW_SIZE-1-t}",
        f"pollution_t-{WINDOW_SIZE-1-t}"
    ]

df_windows = pd.DataFrame(X_flat, columns=feature_names)
df_windows["label"] = le.inverse_transform(y_enc[:len(df_windows)])

df_windows.to_csv("windowed_timeseries_dataset.csv", index=False)

print("✅ Saved: windowed_timeseries_dataset.csv")
print("Shape:", df_windows.shape)
print("\nSample window:")
print(df_windows.head(2))

"""🧩 CELL 7 — TinyML-Optimized Conv1D Model"""

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(WINDOW_SIZE, 4)),
    layers.Conv1D(8, kernel_size=3, activation='relu'),
    layers.Flatten(),
    layers.Dense(8, activation='relu'),
    layers.Dense(len(le.classes_), activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""🧩 CELL 8 — Train & Evaluate FLOAT Model"""

from sklearn.metrics import classification_report, accuracy_score
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)
class_weights = dict(enumerate(class_weights))

model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.1,
    class_weight=class_weights,
    verbose=1
)

y_pred = model.predict(X_test).argmax(axis=1)

print("FLOAT accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=le.classes_))

import joblib

joblib.dump(le, "label_encoder.pkl")
print("✅ Saved label encoder: label_encoder.pkl")
print("Class order:", le.classes_)

# Save trained FLOAT model (before INT8)
model.save("timeseries_conv1d_float.h5")

print("✅ Saved trained float model: timeseries_conv1d_float.h5")
print("Model input shape:", model.input_shape)
print("Model output shape:", model.output_shape)

"""🧩 CELL 9 — INT8 Quantization"""

def representative_dataset():
    for i in range(200):
        yield [X_train[i:i+1].astype(np.float32)]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

with open("timeseries_tinyml_int8.tflite", "wb") as f:
    f.write(tflite_model)

print("INT8 model size (bytes):", len(tflite_model))

"""🧩 CELL 10 — Evaluate INT8 Model"""

interpreter = tf.lite.Interpreter(model_path="timeseries_tinyml_int8.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

in_scale, in_zero = input_details[0]['quantization']
out_scale, out_zero = output_details[0]['quantization']

y_pred_int8 = []

for x in X_test:
    x_q = x / in_scale + in_zero
    x_q = np.clip(x_q, -128, 127).astype(np.int8)
    x_q = np.expand_dims(x_q, axis=0)

    interpreter.set_tensor(input_details[0]['index'], x_q)
    interpreter.invoke()

    out = interpreter.get_tensor(output_details[0]['index'])[0]
    out = (out.astype(np.float32) - out_zero) * out_scale
    y_pred_int8.append(np.argmax(out))

print("INT8 accuracy:", accuracy_score(y_test, y_pred_int8))
print(classification_report(y_test, y_pred_int8, target_names=le.classes_))
